import type { Product } from './types';

export const CATEGORIES: string[] = ["All", "men's clothing", "women's clothing", "jewelery", "electronics"];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    title: "Classic Cotton Tee",
    price: 25.99,
    description: "A timeless classic. This 100% cotton tee is soft, breathable, and built to last. Perfect for any casual occasion.",
    category: "men's clothing",
    image: "https://picsum.photos/id/1025/400/500",
  },
  {
    id: 2,
    title: "Slim Fit Denim Jeans",
    price: 89.95,
    description: "Modern slim fit jeans crafted from premium stretch denim for ultimate comfort and style. A wardrobe essential.",
    category: "men's clothing",
    image: "https://picsum.photos/id/1080/400/500",
  },
  {
    id: 3,
    title: "Flowy Summer Blouse",
    price: 45.0,
    description: "Light and airy, this blouse is perfect for warm summer days. Features a delicate floral print and a relaxed fit.",
    category: "women's clothing",
    image: "https://picsum.photos/id/1011/400/500",
  },
  {
    id: 4,
    title: "High-Waisted Skinny Jeans",
    price: 75.5,
    description: "Flatter your figure with these high-waisted skinny jeans. Made with a comfortable stretch fabric that moves with you.",
    category: "women's clothing",
    image: "https://picsum.photos/id/1015/400/500",
  },
  {
    id: 5,
    title: "Silver Dragon Bracelet",
    price: 120.0,
    description: "Intricately designed sterling silver bracelet featuring a dragon motif. A statement piece for any jewelry lover.",
    category: "jewelery",
    image: "https://picsum.photos/id/22/400/500",
  },
  {
    id: 6,
    title: "Gold Plated Hoop Earrings",
    price: 35.0,
    description: "Elegant and versatile, these gold-plated hoop earrings add a touch of sophistication to any outfit.",
    category: "jewelery",
    image: "https://picsum.photos/id/25/400/500",
  },
  {
    id: 7,
    title: "Wireless Bluetooth Headphones",
    price: 99.99,
    description: "Immerse yourself in high-fidelity sound with these comfortable, over-ear wireless headphones. Long battery life and noise-cancellation.",
    category: "electronics",
    image: "https://picsum.photos/id/2/400/500",
  },
  {
    id: 8,
    title: "Men's Leather Jacket",
    price: 250.0,
    description: "A rugged and stylish genuine leather jacket. Perfect for a cool evening out or a motorcycle ride.",
    category: "men's clothing",
    image: "https://picsum.photos/id/1069/400/500",
  },
  {
    id: 9,
    title: "Elegant Evening Dress",
    price: 150.0,
    description: "Turn heads at any formal event with this stunning floor-length evening dress. Features a flattering A-line silhouette.",
    category: "women's clothing",
    image: "https://picsum.photos/id/1074/400/500",
  },
  {
    id: 10,
    title: "Smart Fitness Tracker",
    price: 59.99,
    description: "Track your steps, heart rate, and sleep patterns with this sleek and waterproof fitness tracker.",
    category: "electronics",
    image: "https://picsum.photos/id/0/400/500",
  },
  {
    id: 11,
    title: "Diamond Stud Earrings",
    price: 499.99,
    description: "Classic and brilliant, these diamond stud earrings are a timeless gift and a symbol of elegance.",
    category: "jewelery",
    image: "https://picsum.photos/id/119/400/500",
  },
  {
    id: 12,
    title: "Cozy Knit Sweater",
    price: 65.0,
    description: "Stay warm and stylish in this incredibly soft knit sweater. Perfect for layering during colder months.",
    category: "women's clothing",
    image: "https://picsum.photos/id/367/400/500",
  },
];
